name: "Deploy docs"

on:
  workflow_dispatch:
  workflow_call:
  push:
    tags:
      - '0.*'
    paths:
      - ".dumi/**"
      - "docs/**"
      - "public/**"
      - "src/**"

jobs:
  deploy-docs:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    if: (startsWith(github.ref, 'refs/tags/') && (contains(github.ref_name, '-') == false)) || github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4

      - name: Setup pnpm ğŸ“¦
        run: |
          npm install -g pnpm

      - name: Install and Build ğŸ”§
        run: |
          pnpm install --no-frozen-lockfile
          pnpm docs:build

      - name: Deploy ğŸš€
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
